apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-pv-pod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: task-pv
  template:
    metadata:
      labels:
        app: task-pv
    spec:
      containers:
        - name: data-generate
          image: hwchiu/netutils
          command: ["/bin/sh", "-c"]
          args:
          - |
            while true; do
              echo "$(date) - New data entry" >> /data/data.txt
              sleep 3
            done
          volumeMounts:
          - name: task-pv-storage
            mountPath: "/data"
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
