apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-demo-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-demo-1
  template:
    metadata:
      labels:
        app: secret-demo-1
    spec:
      containers:
        - name: secret-demo-1-server
          image: hwchiu/python-example
          ports:
            - containerPort: 5000
              protocol: "TCP"
          env:
            - name: uname
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: username
          volumeMounts:
          - name: config
            mountPath: "/config"
      volumes:
        - name: config
          secret:
            secretName: mysecret
---
apiVersion: v1
data:
  password: MWYyZDFlMmU2N2Rm
  username: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: null
  name: mysecret













