apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
        - name: www-server
          image: hwchiu/python-example
          ports:
            - containerPort: 5001
              protocol: "TCP"
