apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-deployment-resource
spec:
  replicas: 3
  selector:
    matchLabels:
      app: www-resource
  template:
    metadata:
      labels:
        app: www-resource
    spec:
      containers:
        - name: www-server
          image: hwchiu/python-example
          ports:
            - containerPort: 5000
              protocol: "TCP"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"              
