apiVersion: apps/v1
kind: Deployment
metadata:
  name: signal
  labels:
    app: signal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signal
  template:
    metadata:
      labels:
        app: signal
    spec:
      containers:
      - name: busybox
        image: hwchiu/netutils:python
