apiVersion: apps/v1
kind: Deployment
metadata:
  name: nosignal
  labels:
    app: nosignal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nosignal
  template:
    metadata:
      labels:
        app: nosignal
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sh", "-c", "sleep 3600"]
