# -*- mode: ruby -*-
# vi: set ft=ruby :

cluster = {
  "host1" => { :cpus => 3, :mem => 4096, :ip => "172.17.8.123" },
  "host2" => { :cpus => 2, :mem => 2048, :ip => "172.17.8.124" },
}

Vagrant.configure("2") do |config|
  config.vm.provision :shell, path: "bootstrap.sh"
  cluster.each_with_index do |(hostname, info), index|
      config.vm.define hostname do |cfg|
          cfg.vm.box = "bento/ubuntu-18.04"
          cfg.vm.box_version ='201912.14.0'
          cfg.vm.hostname = hostname
          cfg.vm.network "private_network", ip: info[:ip]
          cfg.vm.provider :virtualbox do |v|
              v.customize ["modifyvm", :id, "--cpus", info[:cpus]]
              v.customize ["modifyvm", :id, "--memory", info[:mem]]
              v.customize ['modifyvm', :id, '--nicpromisc1', 'allow-all']
              v.customize ["modifyvm", :id, "--name", hostname]
          end # end provider
      end # end config
  end # end cluster
end
