apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-affinity4
spec:
  replicas: 10
  selector:
    matchLabels:
      app: podaffinity4
  template:
    metadata:
      labels:
        app: podaffinity4
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    values:
                      - podaffinity1
                    operator: In
              topologyKey: role
      containers:
        - name: www-server
          image: hwchiu/netutils
