apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate-demo
spec:
  replicas: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: recreate
  template:
    metadata:
      labels:
        app: recreate
    spec:
      containers:
        - name: server-1
          image: hwchiu/netutils:python
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "135m" 
          lifecycle:
            preStop:
              exec:
                command:
                  - "bin/bash"
                  - "-c"
                  - "sleep 5"     
