apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-demo
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: rolling
  template:
    metadata:
      labels:
        app: rolling
    spec:
      containers:
        - name: server-1
          image: hwchiu/netutils:python
          resources:
            limits:
              memory: "128Mi"
              cpu: "501m"
            requests:
              memory: "64Mi"
              cpu: "130m" 
          lifecycle:
            preStop:
              exec:
                command:
                  - "bin/bash"
                  - "-c"
                  - "sleep 5"     
